name: network_aware_package
description: A lightweight Flutter package to detect online/offline status.
version: 1.0.1
homepage: https://github.com/Jay-Patel-070/network_aware_package
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

license: MIT